Error:  COMPILATION ERROR :
Error:  /home/runner/work/SwingSet3/SwingSet3/swingx-core/src/test/java/org/jdesktop/swingx/JXTreeTableIssues.java:[210,59]
incompatible types: javax.swing.JTree cannot be converted to
org.jdesktop.swingx.JXTree
[INFO] 1 error