MotifLookAndFeel is deprecated and marked for removal
wg. https://github.com/homebeaver/SwingSet/issues/3

on Windows:
COMPILATION ERROR: package com.sun.java.swing.plaf.motif does not exist