aufgeräumt wg.
https://github.com/homebeaver/UoM/issues/1

und Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException: Cannot invoke
"java.awt.Color.brighter()" because the return value of
"java.awt.Component.getBackground()" is null
	at java.desktop/javax.swing.border.EtchedBorder.getHighlightColor(EtchedBorder.java:248)
	at java.desktop/javax.swing.border.EtchedBorder.paintBorder(EtchedBorder.java:191)
	at java.desktop/javax.swing.JComponent.paintBorder(JComponent.java:1012)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1120)
	at java.desktop/javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:170)
	at org.jdesktop.swingx.plaf.basic.BasicXComboBoxUI$1.paintComponent(BasicXComboBoxUI.java:115)