subclass org.hamcrest.BaseMatcher because ...
error: The type ArgumentMatcher<T> cannot be the superclass of
EquivalentMatcher; a superclass must be a class

Note: since mockito 2.1.0 ArgumentMatcher is an interface